Backup dump of database with rooms

diff --git a/docker-compose-deploy.yaml b/docker-compose-deploy.yaml
--- a/docker-compose-deploy.yaml
+++ b/docker-compose-deploy.yaml
@@ -25,15 +25,19 @@ services:
     labels:
       - "kop.bind.ip=${KOP_BIND_IP}"
       - "traefik.enable=true"
-      - "traefik.http.services.${TRAEFIK_SERVICE}.loadbalancer.server.port=${APP_HOST_PORT}"
+      - "traefik.http.services.${TRAEFIK_SERVICE}.loadbalancer.server.port=${AP\
+        P_HOST_PORT}"
       - "traefik.http.routers.${TRAEFIK_SERVICE}-http.rule=Host(`${HOSTNAME}`)"
       - "traefik.http.routers.${TRAEFIK_SERVICE}-http.entrypoints=http"
-      - "traefik.http.routers.${TRAEFIK_SERVICE}-http.middlewares=redirect-to-https@file"
+      - "traefik.http.routers.${TRAEFIK_SERVICE}-http.middlewares=redirect-to-h\
+        ttps@file"
       - "traefik.http.routers.${TRAEFIK_SERVICE}-http.service=${TRAEFIK_SERVICE}"
       - "traefik.http.routers.${TRAEFIK_SERVICE}-https.rule=Host(`${HOSTNAME}`)"
       - "traefik.http.routers.${TRAEFIK_SERVICE}-https.entrypoints=https"
-      - "traefik.http.routers.${TRAEFIK_SERVICE}-https.middlewares=publicSecurityHeaders@file"
-      - "traefik.http.routers.${TRAEFIK_SERVICE}-https.service=${TRAEFIK_SERVICE}"
+      - "traefik.http.routers.${TRAEFIK_SERVICE}-https.middlewares=publicSecuri\
+        tyHeaders@file"
+      - "traefik.http.routers.${TRAEFIK_SERVICE}-https.service=${TRAEFIK_SERVIC\
+        E}"
     networks:
       - navNet
     volumes:
@@ -53,10 +57,28 @@ services:
       - POSTGRES_DB=${POSTGRES_DB}
     volumes:
       - postgres-data:/var/lib/postgresql
+      - ./backup.dump:/tmp/backup.dump
     security_opt:
       - no-new-privileges:true
     networks:
       - navNet
+    entrypoint:
+      - /bin/sh
+      - -c
+      - |
+        cat <<EOF > /docker-entrypoint-initdb.d/restore.sh
+        #!/bin/bash
+        set -e
+        if [ ! -f /tmp/backup.dump ]; then
+          echo "WARNING: /tmp/backup.dump not found or is not a file. Skipping restore."
+          exit 0
+        fi
+        echo "Restoring database..."
+        pg_restore -U "$$POSTGRES_USER" -d "$$POSTGRES_DB" -v /tmp/backup.dump
+        EOF
+
+        # Hand over to the official Postgres entrypoint
+        exec /usr/local/bin/docker-entrypoint.sh postgres -c "max_wal_size=4GB"
 
 volumes:
   postgres-data:
